----------------------
--- COLORS
----------------------
#define COLOR_BLACK 0x0000
#define COLOR_WHITE 0xFFFF
#define COLOR_GREEN 0x1FEA
#define COLOR_DARKBLUE 0x0AB1
#define COLOR_DARKBLUE_2 0x0169
#define COLOR_DARKBLUE_3 0x01AB
#define COLOR_BLUE
#define COLOR_YELLOW 0xFE60
#define COLOR_ORANGE 0xFE60
#define COLOR_RED 0xF800
#define COLOR_LIGHT_GREY 0x8C71
#define COLOR_GREY 0x7BCF
#define COLOR_DARK_GREY 0x5AEB
#define COLOR_LIGHTRED 0xF9A0
#define COLOR_BARS_2 0x10A3

#define COLOR_BATTERY COLOR_YELLOW
--#define COLOR_LABEL COLOR_GREY
#define COLOR_LABEL COLOR_BLACK
#define COLOR_TEXT COLOR_WHITE
#define COLOR_TEXTEX COLOR_WHITE
--#define COLOR_BG COLOR_DARKBLUE_2
#define COLOR_BG COLOR_DARKBLUE
#define COLOR_BARS COLOR_BLACK
#define COLOR_BARSEX COLOR_BARS_2
#define COLOR_LINES COLOR_WHITE
#define COLOR_NOTELEM COLOR_RED

#define COLOR_CRIT COLOR_RED
#define COLOR_WARN COLOR_YELLOW

#define COLOR_SENSORS COLOR_DARKBLUE_2
#define COLOR_SENSORS_LABEL COLOR_LIGHT_GREY
#define COLOR_SENSORS_TEXT COLOR_WHITE
