#define PARSE_STATE_IDLE 0
#define PARSE_STATE_ERROR 1
#define PARSE_STATE_GOT_START 2
#define PARSE_STATE_GOT_LEN 3
#define PARSE_STATE_GOT_SEQ 4
#define PARSE_STATE_GOT_MSGID 5
#define PARSE_STATE_GOT_PAYLOAD 6
#define PARSE_STATE_MESSAGE_RECEIVED 7

#define SPORT_DATA_FRAME 0x10
#define SPORT_UPLINK_FRAME 0x30
#define SPORT_DOWNLINK_FRAME 0x32
#define SPORT_UPLINK_SENSOR_ID 0x0D

#define SPORT_BUFFER_SIZE 50
-- MAVLITE_MAX_PAYLOAD_LEN= 1 + 2 + 7x4
#define MAVLITE_MAX_PAYLOAD_LEN 31

#define DEBUG_SPORT
#define DEBUG_MAVLITE

