-- This file was automatically generated by FrskyLuaGCSGui

local description = "Copter params"

local parameters = {
--[[
  Controls which parameters (normally PID gains) are being tuned with transmitter's channel 6 knob
--]]
{"TUNE",{"None","Stab Roll/Pitch kP","Stab Yaw kP","Rate Roll/Pitch kP","Rate Roll/Pitch kI","Rate Yaw kP","Throttle Rate kP","WP Speed","Loiter Pos kP","Heli Ext Gyro","AltHold kP","Rate Roll/Pitch kD","Velocity XY kP","Acro RollPitch kP","Rate Yaw kD","Velocity XY kI","Throttle Accel kP","Throttle Accel kI","Throttle Accel kD","Declination","Circle Rate","Acro Yaw kP","RangeFinder Gain","RC Feel","Rate Pitch kP","Rate Pitch kI","Rate Pitch kD","Rate Roll kP","Rate Roll kI","Rate Roll kD","Rate Pitch FF","Rate Roll FF","Rate Yaw FF","Motor Yaw Headroom","Rate Yaw Filter","Winch","SysID Magnitude",},{0,1,3,4,5,6,7,10,12,13,14,21,22,25,26,28,34,35,36,38,39,40,41,45,46,47,48,49,50,51,52,53,54,55,56,57,58,}},

--[[
  Maximum value that the parameter currently being tuned with the transmitter's channel 6 knob will be set to
--]]
{"TUNE_MAX",-1000000,1000000,.1,"",},

--[[
  Minimum value that the parameter currently being tuned with the transmitter's channel 6 knob will be set to
--]]
{"TUNE_MIN",-1000000,1000000,.1,"",},

--[[
  Maximum lean angle in all flight modes
--]]
{"ANGLE_MAX",1000,8000,10,"cdeg",},

--[[
  Loiter maximum lean angle. Set to zero for 2/3 of PSC_ANGLE_MAX or ANGLE_MAX
--]]
{"LOIT_ANG_MAX",0,45,1,"deg",},

--[[
  Defines the maximum speed in cm/s which the aircraft will travel horizontally while in loiter mode
--]]
{"LOIT_SPEED",20,2000,50,"cm/s",},

--[[
  Compensates for the roll angle difference between the control board and the frame. Positive values make the vehicle roll right.
--]]
{"AHRS_TRIM_X",-0.1745,0.1745,0.01,"rad",},

--[[
  Compensates for the pitch angle difference between the control board and the frame. Positive values make the vehicle pitch up/back.
--]]
{"AHRS_TRIM_Y",-0.1745,0.1745,0.01,"rad",},

--[[
  Defines the speed in cm/s which the aircraft will attempt to maintain horizontally during a WP mission
--]]
{"WPNAV_SPEED",50,2000,50,"cm/s",},

--[[
  The maximum vertical descending velocity the pilot may request in cm/s
--]]
{"PILOT_SPEED_DN",50,500,10,"cm/s",},

--[[
  The maximum vertical ascending velocity the pilot may request in cm/s
--]]
{"PILOT_SPEED_UP",50,500,10,"cm/s",},

}
return { list = parameters,description = description}
-- test change
