-- This file was automatically generated by FrskyLuaGCSGui

local description = "Plane Tune"

local parameters = {
--[[
  Proportional gain from roll angle demands to ailerons. Higher values allow more servo response but can cause oscillations. Automatically set and adjusted by AUTOTUNE mode.
--]]
{"RLL2SRV_P",0.1,4.0,0.1,"",},

--[[
  Integrator gain from long-term roll angle offsets to ailerons. Higher values "trim" out offsets faster but can cause oscillations. Automatically set and adjusted by AUTOTUNE mode.
--]]
{"RLL2SRV_I",0,1.0,0.05,"",},

--[[
  Damping gain from roll acceleration to ailerons. Higher values reduce rolling in turbulence, but can cause oscillations. Automatically set and adjusted by AUTOTUNE mode.
--]]
{"RLL2SRV_D",0,0.2,0.01,"",},

--[[
  Proportional gain from pitch angle demands to elevator. Higher values allow more servo response but can cause oscillations. Automatically set and adjusted by AUTOTUNE mode.
--]]
{"PTCH2SRV_P",0.1,3.0,0.1,"",},

--[[
  Integrator gain from long-term pitch angle offsets to elevator. Higher values "trim" out offsets faster but can cause oscillations. Automatically set and adjusted by AUTOTUNE mode.
--]]
{"PTCH2SRV_I",0,0.5,0.05,"",},

--[[
  Damping gain from pitch acceleration to elevator. Higher values reduce pitching in turbulence, but can cause oscillations. Automatically set and adjusted by AUTOTUNE mode.
--]]
{"PTCH2SRV_D",0,0.2,0.01,"",},

--[[
  Gain from lateral acceleration to demanded yaw rate for aircraft with enough fuselage area to detect lateral acceleration and sideslips. Do not enable for flying wings and gliders. Actively coordinates flight more than just yaw damping. Set after YAW2SRV_DAMP and YAW2SRV_INT are tuned.
--]]
{"YAW2SRV_SLIP",0,4,0.25,"",},

--[[
  Integral gain from lateral acceleration error. Effectively trims rudder to eliminate long-term sideslip.
--]]
{"YAW2SRV_INT",0,2,0.25,"",},

--[[
  Gain from yaw rate to rudder. Most effective at yaw damping and should be tuned after KFF_RDDRMIX. Also disables YAW2SRV_INT if set to 0.
--]]
{"YAW2SRV_DAMP",0,2,0.25,"",},

--[[
  This sets which parameter or set of parameters will be tuned. Values greater than 100 indicate a set of parameters rather than a single parameter. Parameters less than 50 are for QuadPlane vertical lift motors only.
--]]
{"TUNE_PARAM",{"None","RateRollPI","RateRollP","RateRollI","RateRollD","RatePitchPI","RatePitchP","RatePitchI","RatePitchD","RateYawPI","RateYawP","RateYawI","RateYawD","AngleRollP","AnglePitchP","AngleYawP","PosXYP","PosZP","VelXYP","VelXYI","VelZP","AccelZP","AccelZI","AccelZD","FixedWingRollP","FixedWingRollI","FixedWingRollD","FixedWingRollFF","FixedWingPitchP","FixedWingPitchI","FixedWingPitchD","FixedWingPitchFF","Set_RateRollPitch","Set_RateRoll","Set_RatePitch","Set_RateYaw","Set_AngleRollPitch","Set_VelXY","Set_AccelZ",},{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,50,51,52,53,54,55,56,57,101,102,103,104,105,106,107,}},

--[[
  Gain added to pitch to keep aircraft from descending or ascending in turns. Increase in increments of 0.05 to reduce altitude loss. Decrease for altitude gain.
--]]
{"PTCH2SRV_RLL",0.7,1.5,0.05,"",},

--[[
  This sets the range over which tuning will change a parameter. A value of 2 means the tuning parameter will go from 0.5 times the start value to 2x the start value over the range of the tuning channel
--]]
{"TUNE_RANGE",0,4,1,"",},

}
return { list = parameters,description = description}
